name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pytorch torchvision torchaudio cpuonly -c pytorch
          pip install -e .
          pip install -U --force-reinstall chardet charset-normalizer
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          pip install httpx
          pip install pytest
          pip install pytest-cov
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov --durations=0
